version: '3.3'

services:
  www:
    build: ./php
    image: foritel/php:7.0-apache-ext
    networks:
      - web
    labels:
      - "traefik.frontend.rule=HostRegexp:${DOMAIN}.dev2.directline.pro,{subdomain:.*}.${DOMAIN}.dev2.directline.pro"
      - "traefik.frontend.auth.basic=${BASIC_AUTH_USERS}"
    volumes:
      - "./php.ini:/usr/local/etc/php/conf.d/90-user.ini"
      - "www:/var/www/html"
      - "logs:/var/log"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
volumes:
  www:
    driver: local-persist
    driver_opts:
      mountpoint: /var/www/docker/${DOMAIN}/www_test
  logs:
    driver: local-persist
    driver_opts:
      mountpoint: /var/www/docker/${DOMAIN}/logs
networks:
  web:
    external:
      name: traefik_overlay
